config/routes.rb
Rails.application.routes.draw do
root "static_pages#index"
resources :users, only: :show

  get '/signup', to: "registrations#new", as: 'new_registration'
  post '/signup', to: "registrations#create", as: 'registration'

  get '/login', to: "sessions#new", as: 'new_login'
  post '/login', to: "sessions#create", as: 'login'
  delete '/logout', to: "sessions#destroy", as: 'logout'

get 'auth/facebook/callback', to: 'sessions#create'
get 'auth/failure', to: 'static_page#index'
get '/signout' => 'sessions#destroy', :as => :signout

end

app/models/add_user_column.rb
class AddUserColumn < ActiveRecord::Base
end

app/models/concerns/listing.rb
class Listing < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def new_login_path(scope)
    new_login_path
  end

  private
  def authenticate_user!
  	flash[:notice] = "Please login first"
  	redirect_to root_path unless user_logged_in?
  end

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
helper_method :current_user

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:notice] = "You have succesfully signed up"
			login(@user)
      redirect_to @user
    else
    	render :new
    end
	end

	 private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :address, :phone_number)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@user = User.find_by(email: params[:login][:email])
		if @user && @user.authenticate(params[:login][:password])
			login(@user)
			redirect_to @user
		else
			flash[:error] = "Email or password is invalid"
			redirect_to new_login_path
		end
	end

	def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def login(user)
		session[:user_id] = user.id
	end

	def current_user
		User.find(session[:user_id]) if session[:user_id]
	end

	def user_logged_in?
		!current_user.nil?
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sukiairbnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% flash.each do |k, v| %>
	<p><%= "#{k}: #{v}"%></p>
	<% end %>

<%= yield %>

<% if user_logged_in? %>
<%= link_to "Logout", logout_path, method: :delete %>
<% end %>

<div id="user_nav">
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
  <% end %>
</div>

</body>
</html>
				
 

app/views/static_pages/index.html.erb
<h1> Suki AirBnb</h1>

<p>
<%= link_to "Sign Up", new_registration_path %>
<%= link_to "Login", new_login_path %>
</p>

app/views/users/show.html.erb
<h1>Hello, <%= @user.first_name%></h1>